// Output escaping and known input-hardening gaps. The data is generated by an
// LLM pipeline over WhatsApp messages, so provider-controlled strings (names,
// quotes, websites) are effectively untrusted.
import { afterEach, describe, expect, test } from "vitest";
import { boot, closeAll } from "./harness.js";

afterEach(closeAll);

function cardByTitle($$, title) {
  return $$(".card:not(.skeleton)").find((c) => c.querySelector("h3")?.textContent === title);
}

// One entry per hardening concern; category "plumbing" keeps them all visible.
function withEntry(extra) {
  return {
    categories: [{ slug: "plumbing", name: "Plumbing", emoji: "🔧", entry_count: 1 }],
    entries: [{
      id: "t", category: "plumbing", name: "Target Co",
      contact: { phones: [], emails: [], websites: [] },
      mentions: [{ quote: "ok", by: "N", date: "2026-07-01", msg_id: "m", type: "review" }],
      first_seen: "2026-07-01", last_seen: "2026-07-01", mention_count: 1,
      ...extra,
    }],
  };
}

describe("HTML escaping (esc)", () => {
  test("special characters in a name are escaped, not parsed as markup", async () => {
    const { $$ } = await boot(); // default fixtures include the 'Escape & Co <x> "test"' entry
    const card = cardByTitle($$, 'Escape & Co <x> "test"');
    expect(card).toBeTruthy();
    // The '<x>' must be inert text, never a real element.
    expect(card.querySelector("x")).toBeNull();
  });

  test("a <script> payload inside a quote is rendered as literal text", async () => {
    const { $$ } = await boot();
    const card = cardByTitle($$, 'Escape & Co <x> "test"');
    expect(card.querySelector("script")).toBeNull();
    expect(card.querySelector(".quote").textContent)
      .toContain('<script>alert(1)</script> & "quotes"');
  });
});

describe("fmtDate guards", () => {
  test("a non-ISO date string is passed through unchanged", async () => {
    const { $$ } = await boot(withEntry({
      mentions: [{ quote: "ok", by: "N", date: "2026", msg_id: "m", type: "review" }],
    }));
    // "2026" has no day/month parts, so fmtDate returns it verbatim.
    expect(cardByTitle($$, "Target Co").querySelector(".attribution").textContent).toContain("2026");
  });

  test("out-of-range month falls back to the raw string instead of 'undefined'", async () => {
    const { $$ } = await boot(withEntry({
      mentions: [{ quote: "ok", by: "N", date: "2026-13-22", msg_id: "m", type: "review" }],
    }));
    const text = cardByTitle($$, "Target Co").querySelector(".attribution").textContent;
    expect(text).not.toContain("undefined");
    expect(text).toContain("2026-13-22");
  });
});

describe("website URL scheme", () => {
  test("a javascript: website is dropped, never rendered as a live href", async () => {
    const { $$ } = await boot(withEntry({
      contact: { phones: [], emails: [], websites: ["javascript:alert(document.cookie)"] },
    }));
    const card = cardByTitle($$, "Target Co");
    const anchors = [...card.querySelectorAll("a")];
    expect(anchors.some((a) => /^javascript:/i.test(a.getAttribute("href") || ""))).toBe(false);
    // No usable contact remains, so the fallback note is shown.
    expect(card.querySelector(".card-foot").textContent).toContain("No contact shared");
  });

  test("other dangerous schemes (data:) are dropped too", async () => {
    const { $$ } = await boot(withEntry({
      contact: { phones: [], emails: [], websites: ["data:text/html,<script>alert(1)</script>"] },
    }));
    const anchors = [...cardByTitle($$, "Target Co").querySelectorAll("a")];
    expect(anchors.some((a) => /^data:/i.test(a.getAttribute("href") || ""))).toBe(false);
  });

  test("a normal https website is preserved verbatim", async () => {
    const { $$ } = await boot(withEntry({
      contact: { phones: [], emails: [], websites: ["https://good.example.com/x"] },
    }));
    const link = cardByTitle($$, "Target Co").querySelector(".contact-main[target='_blank']");
    expect(link.getAttribute("href")).toBe("https://good.example.com/x");
  });

  test("a bare domain is upgraded to https rather than left as a broken relative link", async () => {
    const { $$ } = await boot(withEntry({
      contact: { phones: [], emails: [], websites: ["gmail.com"] },
    }));
    const link = cardByTitle($$, "Target Co").querySelector(".contact-main[target='_blank']");
    expect(link.getAttribute("href")).toBe("https://gmail.com");
    expect(link.querySelector("span").textContent).toBe("gmail.com");
  });
});
